"""add_profile_fields

Revision ID: 239c7e225cb1
Revises: 7b497f8cc95a
Create Date: 2026-05-15 22:54:26.803521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239c7e225cb1'
down_revision: Union[str, Sequence[str], None] = '7b497f8cc95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('users', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('sharing_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'sharing_preferences')
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'role')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
